name: Bug Report Windows
description: Report an issue with the Windows version of the FTB App
title: "[Windows][Bug]: "
labels: [bug, os/windows]
body:
  - type: input
    id: appversion
    attributes:
      label: App Version
      description: |
        What version of the app are you having issues with?
        You can find the app version at the bottom of the settings page in the app
      placeholder: ex. 202103260308-5fe58412e0-prototyping
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log Files
      description: "Link(s) to any log files that may help debug your issue"
      placeholder: https://pste.ch/dotedubine
    validations:
      required: false
  - type: input
    id: debugcode
    attributes:
      label: Debug Code
      description: |
        Please run the following tool and provide the code given.
        https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe
      placeholder: FTB-DBGTEVOISQIRA
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Information
      options:
        - label: I have provided as much information as possible
          required: true
