name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'main'
            name: 'program'
            compress: 'true'
            dest: 'dist'
      - name: Atrifacts
        uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: dist
